#!/bin/bash
#SBATCH -A CLI185
#SBATCH -J NA_AOI_inputdataGEN
#SBATCH -p batch_ccsi
#SBATCH -N 1
#SBATCH -t 24:00:00
#SBATCH --mem=500GB


module load python/3.11-anaconda3
source activate /ccsopen/home/wangd/compEnv

cd /gpfs/wolf2/cades/cli185/proj-shared/wangd/kiloCraft/NA_inputGEN/

date

#===== forcing data

export forcing_input_path="/gpfs/wolf2/cades/cli185/proj-shared/wangd/Forcing_2014/daymet4_1d/"
export output_path="/gpfs/wolf2/cades/cli185/proj-shared/wangd/kiloCraft/NA_domainGEN/NA_AOI_datasets/AKSP/"
export AOI_gridID_path="/gpfs/wolf2/cades/cli185/proj-shared/wangd/kiloCraft/NA_domainGEN/"
export AOI_gridID_file="AKSP_domain.lnd.Daymet_NA.1km.1d.c240403.nc"

python NA_AOI_forcingGEN.py $forcing_input_path $output_path $AOI_gridID_path $AOI_gridID_file


#export output_path="/gpfs/wolf2/cades/cli185/proj-shared/wangd/kiloCraft/NA_domainGEN/temp/MOFlux_production"
#export AOI_gridID_file="MOFlux_domain.lnd.Daymet_GSWP3_TESSFA.4km.1d.c240323.nc"

#python NA_AOI_forcingGEN.py $input_path $output_path $AOI_gridID_path $AOI_gridID_file 

#===== surfdata generation

export surfdata_input_path="/gpfs/wolf2/cades/cli185/proj-shared/wangd/kiloCraft/NA_surfdataGEN/"
export surfdata_file="surfdata.Daymet_NA.1km.1d.c240327.nc"
#python NA_AOI_surfdataGEN.py $surfdata_input_path $surfdata_file $output_path $AOI_gridID_path $AOI_gridID_file 

